[pytest]
norecursedirs = scripts .git .local_backups .model_backups .pytest_cache

pythonpath = .

markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    integration: marks tests as integration tests
