"""Extracted vocabulary from Gutenberg English-Esperanto Dictionary.

This file is auto-generated by scripts/extract_dictionary_roots.py.
To populate this vocabulary, run:
    python scripts/extract_dictionary_roots.py

For now, this is initialized with an empty set.
The parser will fall back to its hardcoded KNOWN_ROOTS vocabulary.
"""

# Roots extracted from dictionary
DICTIONARY_ROOTS = set()

# Prepositions extracted from dictionary
PREPOSITIONS = set()

# Conjunctions extracted from dictionary
CONJUNCTIONS = set()
