#!/bin/bash
# Run Stage 2 grammatical model training
#
# Usage:
#   ./scripts/run_stage2_training.sh [--fresh]
#
# This trains the grammatical model on minimal pairs data.
# Requires:
#   - Stage 1 models in models/root_embeddings/ and models/affix_transforms_v2/
#   - Minimal pairs data in data/training/stage2_pairs.jsonl
#     (generated by scripts/training/generate_stage2_pairs.py)

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_ROOT"

# Activate venv
if [ -d ".venv" ]; then
    source .venv/bin/activate
elif [ -d "venv" ]; then
    source venv/bin/activate
else
    echo "Error: No virtual environment found"
    exit 1
fi

# Parse arguments
FRESH_FLAG=""
if [[ "$1" == "--fresh" ]]; then
    FRESH_FLAG="--fresh"
    echo "Starting fresh training (ignoring checkpoint)"
fi

# Check for required files
if [ ! -f "models/root_embeddings/best_model.pt" ]; then
    echo "Error: Stage 1 root embeddings not found"
    echo "Run Stage 1 training first: ./scripts/run_root_embeddings_training.sh"
    exit 1
fi

if [ ! -f "data/training/stage2_pairs.jsonl" ]; then
    echo "Error: Stage 2 training data not found"
    echo "Generate it first: python scripts/training/generate_stage2_pairs.py"
    exit 1
fi

# Create directories
mkdir -p models/grammatical_transforms
mkdir -p logs

# Run training
LOG_FILE="logs/train_grammatical_$(date +%Y%m%d_%H%M%S).log"
echo "Training Stage 2 grammatical model..."
echo "Log file: $LOG_FILE"
echo ""

python scripts/training/train_grammatical_model.py \
    --stage1-model models/root_embeddings/best_model.pt \
    --affix-model models/affix_transforms_v2/best_model.pt \
    --training-data data/training/stage2_pairs.jsonl \
    --output-dir models/grammatical_transforms \
    --log-dir logs \
    --epochs 50 \
    --batch-size 32 \
    --learning-rate 0.001 \
    --patience 5 \
    $FRESH_FLAG \
    2>&1 | tee "$LOG_FILE"

echo ""
echo "Training complete!"
echo "Model saved to: models/grammatical_transforms/"
echo "Log saved to: $LOG_FILE"
