#!/usr/bin/env python3
"""
Train Entity Type Classifier.

Trains GNN-based classifier on data generated by generate_entity_training_data.py.

Usage:
    python scripts/train_entity_classifier.py \\
        --data data/training/entity_classifier \\
        --output models/entity_classifier \\
        --epochs 50

Features:
- Checkpoint resume (--resume)
- Early stopping (patience=5)
- Validation monitoring
- Atomic checkpoint saves
"""

import argparse
import logging
import json
import sys
from pathlib import Path
from typing import Dict, List, Tuple
import time

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from klareco.models.entity_classifier import (
    EntityTypeClassifier,
    create_deterministic_feature_vector,
    save_checkpoint,
    load_checkpoint
)
from klareco.ast_to_graph import ASTToGraphConverter
from klareco.semantic_enrichment.taxonomy import EntityType, PersonType, LocationType, TimeType, ThingType

try:
    from torch_geometric.data import Data, Batch
    TORCH_GEOMETRIC_AVAILABLE = True
except ImportError:
    TORCH_GEOMETRIC_AVAILABLE = False
    print("ERROR: torch-geometric required. Install with: pip install torch-geometric")
    sys.exit(1)

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


class EntityTypeDataset(Dataset):
    """Dataset for entity type classification."""

    def __init__(self, data_path: Path, ast_converter: ASTToGraphConverter):
        """
        Initialize dataset.

        Args:
            data_path: Path to JSONL file (train.jsonl or val.jsonl)
            ast_converter: ASTToGraphConverter instance
        """
        self.examples = []
        self.ast_converter = ast_converter

        logger.info(f"Loading dataset from {data_path}")

        with open(data_path, 'r') as f:
            for line in f:
                if not line.strip():
                    continue

                try:
                    example = json.loads(line)
                    self.examples.append(example)
                except json.JSONDecodeError:
                    continue

        logger.info(f"Loaded {len(self.examples)} examples")

    def __len__(self) -> int:
        return len(self.examples)

    def __getitem__(self, idx: int) -> Tuple[Data, torch.Tensor, int]:
        """
        Get dataset item.

        Returns:
            (graph_data, deterministic_features, tier3_label)
        """
        example = self.examples[idx]

        # Convert AST to graph
        word_ast = example['word_ast']
        # Create minimal sentence AST for conversion
        sentence_ast = {
            'tipo': 'frazo',
            'verbo': word_ast,  # Put word as verb for simplicity
            'subjekto': None,
            'objekto': None,
            'aliaj': []
        }

        graph = self.ast_converter.ast_to_graph(sentence_ast)

        # Extract deterministic priors
        det_priors = example['deterministic_priors']
        det_features = create_deterministic_feature_vector(det_priors)

        # Extract label
        label_tier3 = example['label']['tier3_type']

        # Map tier3_type string to index
        tier3_index = self._tier3_to_index(label_tier3)

        return graph, det_features, tier3_index

    def _tier3_to_index(self, tier3_str: str) -> int:
        """
        Map tier3 type string to class index.

        Uses combined index across all Tier 3 families.
        """
        # Try each Tier 3 family
        for enum_class in [PersonType, LocationType, TimeType, ThingType]:
            try:
                tier3_enum = enum_class(tier3_str)
                return list(enum_class).index(tier3_enum)
            except ValueError:
                continue

        # Default to 0 if not found
        logger.warning(f"Unknown tier3 type: {tier3_str}, defaulting to 0")
        return 0


def collate_fn(batch: List[Tuple[Data, torch.Tensor, int]]) -> Tuple[Batch, torch.Tensor, torch.Tensor]:
    """
    Collate function for DataLoader.

    Args:
        batch: List of (graph, det_features, label) tuples

    Returns:
        (batched_graphs, batched_det_features, labels)
    """
    graphs, det_features, labels = zip(*batch)

    # Batch graphs
    batched_graphs = Batch.from_data_list(graphs)

    # Stack deterministic features
    batched_det_features = torch.stack(det_features)

    # Stack labels
    batched_labels = torch.tensor(labels, dtype=torch.long)

    return batched_graphs, batched_det_features, batched_labels


def compute_metrics(
    model: EntityTypeClassifier,
    dataloader: DataLoader,
    device: str
) -> Dict[str, float]:
    """
    Compute evaluation metrics.

    Args:
        model: EntityTypeClassifier
        dataloader: Validation DataLoader
        device: Device to run on

    Returns:
        Dictionary with metrics
    """
    model.eval()

    total_correct_tier3 = 0
    total_correct_tier2 = 0
    total = 0

    with torch.no_grad():
        for batched_graphs, det_features, labels in dataloader:
            # Move to device
            batched_graphs = batched_graphs.to(device)
            det_features = det_features.to(device)
            labels = labels.to(device)

            # Predict
            predictions = model.predict(
                batched_graphs.x,
                batched_graphs.edge_index,
                det_features,
                batched_graphs.batch
            )

            # Tier 3 accuracy
            tier3_pred = predictions['tier3_type']
            total_correct_tier3 += (tier3_pred == labels).sum().item()

            total += labels.size(0)

    tier3_accuracy = total_correct_tier3 / total if total > 0 else 0.0

    return {
        'tier3_accuracy': tier3_accuracy,
        'total_examples': total
    }


def train_epoch(
    model: EntityTypeClassifier,
    dataloader: DataLoader,
    optimizer: torch.optim.Optimizer,
    device: str,
    epoch: int
) -> Dict[str, float]:
    """
    Train for one epoch.

    Args:
        model: EntityTypeClassifier
        dataloader: Training DataLoader
        optimizer: Optimizer
        device: Device to run on
        epoch: Current epoch number

    Returns:
        Training metrics
    """
    model.train()

    total_loss = 0.0
    num_batches = 0

    for batch_idx, (batched_graphs, det_features, labels) in enumerate(dataloader):
        # Move to device
        batched_graphs = batched_graphs.to(device)
        det_features = det_features.to(device)
        labels = labels.to(device)

        # Zero gradients
        optimizer.zero_grad()

        # Forward pass
        outputs = model(
            batched_graphs.x,
            batched_graphs.edge_index,
            det_features,
            batched_graphs.batch
        )

        # For now, use combined tier3 loss across all heads
        # In practice, we'd route to correct head based on tier2
        # Simplified: use person_head for all
        tier3_logits = outputs['person_logits']
        loss = nn.functional.cross_entropy(tier3_logits, labels)

        # Backward pass
        loss.backward()
        optimizer.step()

        total_loss += loss.item()
        num_batches += 1

        if (batch_idx + 1) % 10 == 0:
            logger.info(f"Epoch {epoch}, Batch {batch_idx + 1}/{len(dataloader)}, Loss: {loss.item():.4f}")

    avg_loss = total_loss / num_batches if num_batches > 0 else 0.0

    return {
        'train_loss': avg_loss,
        'num_batches': num_batches
    }


def main():
    parser = argparse.ArgumentParser(description='Train entity type classifier')
    parser.add_argument(
        '--data',
        type=Path,
        default=Path('data/training/entity_classifier'),
        help='Path to training data directory'
    )
    parser.add_argument(
        '--output',
        type=Path,
        default=Path('models/entity_classifier'),
        help='Output directory for checkpoints'
    )
    parser.add_argument(
        '--epochs',
        type=int,
        default=50,
        help='Number of training epochs'
    )
    parser.add_argument(
        '--batch-size',
        type=int,
        default=32,
        help='Batch size'
    )
    parser.add_argument(
        '--lr',
        type=float,
        default=0.001,
        help='Learning rate'
    )
    parser.add_argument(
        '--patience',
        type=int,
        default=5,
        help='Early stopping patience'
    )
    parser.add_argument(
        '--resume',
        action='store_true',
        help='Resume from checkpoint'
    )
    parser.add_argument(
        '--device',
        type=str,
        default='cpu',
        help='Device (cpu or cuda)'
    )

    args = parser.parse_args()

    # Create output directory
    args.output.mkdir(parents=True, exist_ok=True)

    # Setup logging to file
    log_file = args.output / 'training.log'
    file_handler = logging.FileHandler(log_file)
    file_handler.setFormatter(logging.Formatter('%(asctime)s - %(levelname)s - %(message)s'))
    logger.addHandler(file_handler)

    logger.info("=" * 60)
    logger.info("ENTITY TYPE CLASSIFIER TRAINING")
    logger.info("=" * 60)
    logger.info(f"Data directory: {args.data}")
    logger.info(f"Output directory: {args.output}")
    logger.info(f"Device: {args.device}")
    logger.info(f"Epochs: {args.epochs}")
    logger.info(f"Batch size: {args.batch_size}")
    logger.info(f"Learning rate: {args.lr}")

    # Initialize AST converter (legacy mode without compositional embeddings)
    ast_converter = ASTToGraphConverter(embed_dim_or_embedding=128)
    node_feature_dim = ast_converter.get_feature_dim()

    logger.info(f"Node feature dimension: {node_feature_dim}")

    # Load datasets
    train_path = args.data / 'train.jsonl'
    val_path = args.data / 'val.jsonl'

    if not train_path.exists():
        logger.error(f"Training data not found: {train_path}")
        logger.error("Run generate_entity_training_data.py first!")
        return 1

    train_dataset = EntityTypeDataset(train_path, ast_converter)
    val_dataset = EntityTypeDataset(val_path, ast_converter) if val_path.exists() else None

    train_loader = DataLoader(
        train_dataset,
        batch_size=args.batch_size,
        shuffle=True,
        collate_fn=collate_fn
    )

    val_loader = None
    if val_dataset:
        val_loader = DataLoader(
            val_dataset,
            batch_size=args.batch_size,
            shuffle=False,
            collate_fn=collate_fn
        )

    # Initialize model
    model = EntityTypeClassifier(
        node_feature_dim=node_feature_dim,
        deterministic_feature_dim=6
    )
    model.to(args.device)

    logger.info(f"Model parameters: {model.count_parameters():,}")

    # Optimizer
    optimizer = optim.Adam(model.parameters(), lr=args.lr)

    # Resume from checkpoint if requested
    start_epoch = 0
    best_val_accuracy = 0.0

    if args.resume:
        checkpoint_path = args.output / 'best_model.pt'
        if checkpoint_path.exists():
            model, metrics = load_checkpoint(checkpoint_path, args.device)
            best_val_accuracy = metrics.get('val_accuracy', 0.0)
            start_epoch = metrics.get('epoch', 0) + 1
            logger.info(f"Resumed from epoch {start_epoch}, best val accuracy: {best_val_accuracy:.4f}")

    # Training loop
    patience_counter = 0

    for epoch in range(start_epoch, args.epochs):
        logger.info(f"\nEpoch {epoch + 1}/{args.epochs}")
        logger.info("-" * 60)

        # Train
        train_metrics = train_epoch(model, train_loader, optimizer, args.device, epoch + 1)
        logger.info(f"Train loss: {train_metrics['train_loss']:.4f}")

        # Validate
        if val_loader:
            val_metrics = compute_metrics(model, val_loader, args.device)
            val_accuracy = val_metrics['tier3_accuracy']
            logger.info(f"Validation Tier 3 accuracy: {val_accuracy:.4f}")

            # Save best model
            if val_accuracy > best_val_accuracy:
                best_val_accuracy = val_accuracy
                patience_counter = 0

                metrics = {
                    'epoch': epoch,
                    'train_loss': train_metrics['train_loss'],
                    'val_accuracy': val_accuracy,
                }

                save_checkpoint(
                    model,
                    optimizer,
                    epoch,
                    metrics,
                    args.output / 'best_model.pt'
                )
                logger.info(f"✓ New best model saved (val accuracy: {val_accuracy:.4f})")
            else:
                patience_counter += 1
                logger.info(f"No improvement ({patience_counter}/{args.patience})")

            # Early stopping
            if patience_counter >= args.patience:
                logger.info(f"Early stopping triggered after {epoch + 1} epochs")
                break

    logger.info("\n" + "=" * 60)
    logger.info("TRAINING COMPLETE")
    logger.info("=" * 60)
    logger.info(f"Best validation accuracy: {best_val_accuracy:.4f}")
    logger.info(f"Model saved to: {args.output / 'best_model.pt'}")

    return 0


if __name__ == '__main__':
    sys.exit(main())
